### ISSUE TITLE
Any example for the usage of this udf

### ISSUE THREAD

**Issue by bustix** [genius257/AutoIt-HTML-Parser#1]
Hello,
thank you for this udf.
Could you please give me an example on how to use this UDF?
Unfortunately I'm not able to get it to work.

**Comment by genius257** [comment]
Hi @bustix 
Thank you for the interest in this project :)
For a quick guide, i would refer you to the [wiki](https://github.com/genius257/AutoIt-HTML-Parser/wiki), but yes an example file should be added, will start making one, shouldn't be long :)

**Comment by bustix** [comment]
Hello, seems like be a really great project and i would love to use it, but actually i dont quite understand it and the wiki is not very detailed :)
The only result i got was by .Next i think or .First - but it was like an ID with 0x123467ABCDEF and i didnt really understood what exactly i got there - or - how to convert it to text haha

**Comment by genius257** [comment]
There are [examples](https://github.com/genius257/AutoIt-HTML-Parser/wiki/_HTMLParser_Element_GetText-Function#example) attached to all methods documented in the wiki.
**.Next** and **.First** are pointers to tokens, holding _type_, _position_ and _length_ of the match.
I've added a simple example file, showing parsing and using two methods with the UDF.
The point of this UDF is to mimic some of the functions you would have available in your browser JavaScript engine, ie: (getElementById, getElementsByClassName or getElementsByTagName), when more flushed out, a object wrapper could be used to make calling methods MUCH simpler and user friendly :)

**Comment by bustix** [comment]
This example did work for me, but it also gives me a lot of empty text back - and like i show you what i mean:
[HTML-Parser.zip](https://github.com/genius257/AutoIt-HTML-Parser/files/3191293/HTML-Parser.zip)

i would love the option to get all i want, for example an array with all informations between each <td> or any other range/command - also to decide to get the text only or the pre/suffix also.

i would also love to commit to this, but for now i still have some problems with the udf.

but i will keep annoying you until i unterstood it :)

Edit: also in your example, it's hard to tell from where he got what - like the empty lines - which harden the debugging - maybe a stringstripws,8,8 + if line<>"" helps this out

Edit2:
btw. as soon as i started to fully understand your lovely udf, i will include it into my framework - if this is ok for you, you are able to the the first steps of it on my profile :)
not much done yet, still gathering informations and build a "FasterObjects.au3" - cause i did not like the old way of the object creation, so i changed it a lil bit.
And i would love to convert your code into object-code too.

**Comment by genius257** [comment]
Hmm I would argue all the empty text is the correct behavior, when retrieving all text nodes from the HTML.
The filtering of empty text with something like `StringStripWS(..., 3) == ""` should be handled by a custom function afterwards, i would say.
I am not sure what you mean by 

> for example an array with all informations between each or any other range/command

You are more than welcome to ask about the UDF, i don't mind :)

Yeah i don't mind you using/modifying/redistributing it :) That's why i use the MIT license for most of my projects :)

**Comment by bustix** [comment]
Like, is it possible, if you have an website with like (TD) blabla (TR)(/TR)... miles of more code (/TD) to get anything (with the HTML!) inside of TD with this UDF? (cant past the code with <> - gets filtered :/)

And i want to convert it into this framework, as soon as I'm finally ready to do it 👍 
https://www.autoitscript.com/forum/topic/198959-object-framework-with-fastobject-xml-translater-multi-processing-wip/?tab=comments#comment-1427724

But before i need to know, if this is possible - cause that would be essential - i need the ability to get HTML code aswell as text only or a mix of both - like in the example above :)

Like for example in the link i did paste you, I'm currently on the XML function to get the source and take on the interaction - and i need an HTML parser, to get specific things of different website and also in different ways (like in the example on top) - cause sometimes i have to keep the formatting which is not always possible (at least for me) [<-regex nub] - and therefore i have to take the HTML code between a node and extract from there on slowy.

the last problem i had, was i had a table | a | b | c | d | | f |
now, when i did the extraction, i had a b c d f - the problem is the empty table was gone - therefore everything went one space to the left and the entire display was messed up for the following tables also.
And because the empty spaces occur randomly, gathering only the text (depending on how i receive them) - is not very good.
When i think about it - maybe the "spaces" in your example, are empty arrays which simulate the empty field in the table..... hmmm

**Comment by genius257** [comment]
I think you are asking if the functions can be applied to an sub element?
If so, then yes :) Here's an example:

```autoit
#include "HTMLParser.au3"

$sHTML = "<html><head><title>test</title></head><body><table><tr><th>A</th><th>B</th><th>C</th></tr><tr><td>A1</td><td>B1</td><td>C1</td></tr><tr><td>A2</td><td>B2</td><td>C2</td></tr><tr><td>A3</td><td>B3</td><td>C3</td></tr></table></html>"

$tTokenList = _HTMLParser($sHTML)

$pItem = _HTMLParser_GetFirstStartTag($tTokenList.First, $sHTML);finds first start tag. In this example it will be <html>

$pTables = _HTMLParser_GetElementsByTagName("table", $pItem, $sHTML);finds all <table>

$pTrs = _HTMLParser_GetElementsByTagName("tr", $pTables[0], $sHTML);finds all <tr>

For $iTr = 0 To UBound($pTrs, 1)-1
    $pTableDataElements = _HTMLParser_Element_GetChildren($pTrs[$iTr], $sHTML)
    For $iTableDataElement = 0 To UBound($pTableDataElements, 1)-1
        $aText = _HTMLParser_Element_GetText($pTableDataElements[$iTableDataElement], $sHTML)

        ;lists all text node found in file
        ;this will be changed for a later version
        For $i=0 To Ubound($aText, 1)-1
            _MemMoveMemory($aText[$i], $__g_pTokenListToken, $__g_iTokenListToken)
            ConsoleWrite( _
                "row: "&$iTr&" col:"&$iTableDataElement&" "& _
                StringStripWS(StringMid($sHTML, $__g_tTokenListToken.Start, $__g_tTokenListToken.Length), 8) _
            &@crlf)
        Next
    Next
Next
```

**Comment by bustix** [comment]
Duuude hahaha but this is in no way comfortable xD i have to find a way to make that more comfortable..
why you dont return stringregexp arrays? working with those would be so much easier for me :/ haha

**Comment by genius257** [comment]
I am sorry ^^'
That's why i plan to wrap it in an object, once it's more release ready :)
stringregexp arrays is a troublesome way to do it with the xml structure, not to mention that way more memory would be used ^^'

**Comment by bustix** [comment]
the memmove you are using is the most confusing thing in this code haha - also the the names for the vars is so confusing to me, gotta read deeply into it - seems like ure more used to c# / c++ coding

**Comment by genius257** [comment]
_MemMoveMemory does not move memory, it copies it (misleading name i know) from one memory address to another
About the variable names, i am not sure what part of them is confusing? but the global ones is named like that to try and avoid naming conflicts, while describing the variable role :)
Well kinda... AutoIt does have some huge problems when it comes to code conventions from other languages. The result is long and obscure function and variable names and most of the time a lot more lines of code :/

**Comment by bustix** [comment]
Hey, sorry for not responding, had the head full :)
Why are you copying the mem address and not reading it directly? 
Ye and confusing, cause im not used to that style of programming - yet, cause it's as far as i'm reading autoit code, not common to use those names for your variables.
are you thinking about converting your parser into an object? 
If yes, any plans on when you are moving on with it?
Cause if i start to convert it, and then you convert it (as you obviously code better then me) - i would just waste time in doing it and focus on other things that i want to convert and add your - better - code to the framework :D

**Comment by genius257** [comment]
No problem :)
It is in an attempt to maybe gain a small amount of speed, by avoiding asking AutoIt to keep allocating/releasing memory for the same DLLStruct with pointer reference moved. I am not sure if using memmove actually is faster or not...
I would say it depends on who writes it ;) some of the naming is based on AutoIt's own wiki page [Best coding practices](https://www.autoitscript.com/wiki/Best_coding_practices).
Yeah i am :) my big problem with doing it is the loss of speed, with calls to the object. I imagine the speed diff is around 50-100 ms, but when calling methods constantly in a loop, it adds up :/
I can convert it to an IDispatch UDF (with my [AutoItObject Internal](https://github.com/genius257/AutoItObject-Internal)) in about a day, however changes need to be made to the way my HTML parser UDF currently handles its internal token references. currently it can't handle parsing and working with more than 1 HTML document at the time.
That will take a few days i think :/
My main motivation for my projects is equal to how much i need it myself, and of course if anyone beside myself is interested :)
I will start working on the internal handling of the tokens tomorrow :)

**Comment by bustix** [comment]
Hey, hope your doing good :)
This sounds great, that you are continueing on this project, love to read that message.
Also with your Autoit Object Internal - to be honest, at first i wanted to use this UDF - but it came with a big issue for me - the code did not run as soon as it got compiled.
If i run the code in scite (and after changing the line feed to CRLF) it did run the code very well.
After compiling the same code and starting the .exe file, i got no result whatsoever, the exe just opened and closed itself afterwards, and i was not able to fix this issue.
Therefore i put it in the deprecated folder for like later inspection. -Btw. sounds good that this is also your UDF, because I'm already in touch with you :)
Do you think your IDispatch UDF is faster then the AutoItObject? If yes, why?
I'm also still not sure, why you are using those tokens, i mean - there should be a lot of different methods on doing this.
Like - as you said - use your IDispatch Objects UDF and store everything in an object.
then you can like $html.load(file) <- file gets instantly loaded and every piece gets extracted and stored.
then for example $html.show() <- returns all found things like ELEMENT:ID:10  (just an example that 10x ID has been found) and ELEMENT:TR:3 etc.
then $html.show(element, 5) <- shows element 5
or $html.show(element, 5, html) <- returns the entire html code for element 5
or $html.show(element, 5, text) <- returns only the text of element 5
or $html.searchAll(ahref) <- returns all ahref elements
or $html.search(ahref, text) <- returns the text of all ahref
or $html.search(ahref, id) <- the name of the ahref field
or $html.search(ahref, id).first()
or $html.search(ahref.id).next() <- oh dude, i could continue with this all day haha :D
or $html.convert(xml) <- converts document to xml
etc.
The list could be endless, but easy to acess and operate with.
something similiar to this, is how i'd like to do it in my framework - would this be far away from your plans? :D
And I'm really interested in both of your UDF's - still for the Internal objects, i would love an explanation on where the difference are between the autoitobject.au3 (from prog@ndy) and your udf - except for the syntax. 
again, thank you for keeping in touch and i wish you a nice day.
kindest regards

**Comment by genius257** [comment]
Hey, yeah most of the time, thanks :)

I have not experienced that issue with AutoItObject Internal, tried to compile the example file just now to x86 and x64, both worked fine for me?
If you want you are more than welcome to [open an issue](https://github.com/genius257/AutoItObject-Internal/issues) in the repository, with an example reproducing the issue :)
I'm not sure if it's faster or not, but AutoItObject need the external dlls to work. Also AutoItObject does not support getters/setters on the objects. That was my initial goal with my UDF :)
My AutoItObject Internal UDF also is in "pure" AutoIt, and it supports ALL variables types from AutoIt. No need to learn a new language (c++ in AutoItObject's case) , if you wish to modify some internal workings of the Object.
It's basic lexer/parser logic. The lexer tokenises the input for feature use by the parser. The parser then uses the tokens to provide a "simple" easily extension-able codebase. There are many articles, books and so on, explaining lexers, parsers and the logic behind them.
The Object wrapper is needed to avoid keeping track of handles and releasing the memory before shutting down the script. The reason this UDF can currently only handle one HTML document at a time, is because, to support working with multiple HTML documents at the same time, would require an additional parameter specifying the LinkedList holding the tokens. An object wrapper would be able to know it's own context and fetch information needed mostly from within the wrapper, making it simpler to the programmer.
Trouble with your example is that it would store collections of elements, but not their position and relation. This is fine for basic extraction, but if usage is a specific DOM path, or the goal is to modify and output HTML, your example approach would not work. But many of the methods in your example can already be done by this UDF.
Side note: HTML is extended XML, so converting it to xml, would only remove elements not supported by xml and maybe some of the attributes.
My plan is indeed to make it easier to work with, but only because there would be a reduced number of parameters to provide each method. The goal is to act like the JavaScript in the browser, when querying elements and manipulating them. It makes the most sense to me, as it's easy for people to migrate JS to AutoIt that way, and the documentation is ~98% referring to JavaScript documentation in terms of method input and output.

No problem, thank you and you too :)
